FROM python:3.6
MAINTAINER denzow <denzow@gmail.com>

EXPOSE 6800
ENV LC_ALL=C.UTF-8 LANG=C.UTF-8

WORKDIR /app

RUN pip install -v pip-tools==1.9.0

ADD requirements.txt requirements.txt
RUN pip-sync /app/requirements.txt

RUN mkdir /etc/scrapyd/ /scrapyd /scrapyd/eggs /scrapyd/logs /scrapyd/dbs
ADD ./docker/scrapyd/scrapyd.conf /etc/scrapyd/scrapyd.conf
ADD ./docker/scrapyd/start-scrapyd.sh /usr/local/bin/start-scrapyd
ADD ./docker/scrapyd/deploy-projects.sh /usr/local/bin/deploy-projects

ADD . /app
WORKDIR /